# Common Labels
labels:
  app: "scheduler"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "scheduler"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "scheduler_schema"
    image:
      repository: "pucarsolutionsdev.azurecr.io/scheduler-svc_db"
      tag: v1.0.0-471b0d2c2f192d122797c17ef344943f7960fb72


# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/scheduler-svc"
  tag: v1.0.0-471b0d2c2f192d122797c17ef344943f7960fb72
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/scheduler/health"
  readinessProbePath: "/scheduler/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx64m -Xms64m"
java-args: "-Dspring.profiles.active=monitoring"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: COURT_ENABLED
    value: "false"
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-url
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: SPRING_FLYWAY_URL
    valueFrom:
      configMapKeyRef:
        key: db-url
        name: egov-config
  - name: SPRING_FLYWAY_USER
    valueFrom:
      secretKeyRef:
        key: username
        name: db
  - name: SPRING_FLYWAY_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_USER_SEARCH_PATH
    value: "/user/v1/_search"
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        key: kafka-brokers
        name: egov-config
  - name: EGOV_PDF_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: pdf-service
  - name: DRISHTI_CASE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: case
  - name: DRISHTI_ANALYTICS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: analytics
  - name: DRISTI_APPLICATION_HOST
    valueFrom:
      configMapKeyRef:
        key: application
        name: egov-service-host
  - name: DRISTHI_HEARING_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: hearing
  - name: EGOV_ADVOCATE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: advocate
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  
  
  
  
  

